site_name: TURNT
nav:
  - Home: index.md
  - About: about.md
  - Code Examples: code-examples.md
  - Content Tabs: content-tabs.md
  - Admonitions: admonitions.md
theme:
  name: material
  palette: 
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light mode
      primary: green
      accent: deep purple

  # Light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Dark mode
      primary: blue
      accent: deep orange
  features:
    - content.code.copy
    - navigation.footer
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  favicon: assets/favicon.ico

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: simple/youtube
      link: https://youtube.com/@james-willett
    - icon: simple/linkedin
      link: https://linkedin.com/in/willettjames

copyright: Copyright &copy; 2024 James Willett